# Generated by Django 6.0.5 on 2026-05-08 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customerrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerRequest',
        ),
    ]
