# Generated by Django 6.0.5 on 2026-05-08 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
        migrations.AddField(
            model_name='car',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/main/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_name',
            field=models.CharField(help_text='Уникальный ключ для JS (например: celeste)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='specs',
            field=models.JSONField(default=dict, help_text='Формат: [["Мощность", "420 л.с."], ["Скорость", "285"]]'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/gallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='cars.car')),
            ],
        ),
    ]
