# Generated by Django 6.0.5 on 2026-05-08 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_images_car_main_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='spec',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
